### ISSUE TITLE
simple-ng-tags - Remove Issue

### ISSUE THREAD

**Issue by sanjaykumar2338** [charlatan154/simple-ng-tags#1]
The remove tags does not removed the current element in list. it just removing the first element.

Like element 1, element 2 , element 3 , element 4

If i remove element 3 then it will remove element 1. after that the first element removed then i click on the element 4 then it remove the element 2.

Please resolve if soon....

**Comment by akisvolanis** [comment]
fixed [176c75](https://github.com/charlatan154/simple-ng-tags/commit/a1d76d7df4c5e48de931c6858d6ff9aba4176c75).
