### ISSUE TITLE
Issue with Angular-CLI and Prod/AOT Build

### ISSUE THREAD

**Issue by bbonet** [charlatan154/simple-ng-tags#2]
Hi Akis,

Thanks so much for creating a tags component that works with reactive forms. 

We're getting ready to deploy to production and when using Angular-CLI with the 'ng build --prod' flag we're getting some errors on the simple-ng-tags component. Have you tried to compile like this yet? Obviously the _tag error is an easy fix but I'm not sure about the other one. Please see the attached image.

Regards,
Brent

<img width="863" alt="screen shot 2017-07-05 at 2 22 36 pm" src="https://user-images.githubusercontent.com/178903/27883365-7fe9413c-618d-11e7-832b-f45364aeeff8.png">

**Comment by akisvolanis** [comment]
fixed with release 0.1.8
